[project]
name = "rag-evaluation-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kilik42", email = "maevins@cps.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.4.3",
    "langchain-openai>=1.6.7",
    "pymupdf>=1.28.2",
]

[project.scripts]
rag-evaluation-system = "rag_evaluation_system:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
